### ISSUE TITLE
Not correctly using Watson service URLs

### ISSUE THREAD

**Issue by snhwang** [snhwang/Unity-Watson-STT-Assistant-TTS#1]
As of 01/28/2020 7PM CDT time zone, this Unity Project works with Unity 2017.2.8f1, IBM Unity SDK 4.1.1, and Unity SDK core 1.2.0. I'm pretty sure it will work with IBM Unity SDK 4.3.0. You just need to delete the unity-sdk-4.1.1 folder and replace it with unity-sdk-4.3.0. I fixed the mistake of not using the Watson service URLs correctly. So, it should now work with different IBM cloud regions. I've only tried it using the Dallas, Washington DC, and London regions.

**Comment by Aoost** [comment]
> As of 01/28/2020 7PM CDT time zone, this Unity Project works with Unity 2017.2.8f1, IBM Unity SDK 4.1.1, and Unity SDK core 1.2.0. I'm pretty sure it will work with IBM Unity SDK 4.3.0. You just need to delete the unity-sdk-4.1.1 folder and replace it with unity-sdk-4.3.0. I fixed the mistake of not using the Watson service URLs correctly. So, it should now work with different IBM cloud regions. I've only tried it using the Dallas, Washington DC, and London regions.

Hi there, I'm getting what looks to be a similar error when I copy my service url verbatim. Not sure where you are adding the repeated lines though?
ERROR] URL: https://api.us-south.assistant.watson.cloud.ibm.com/instances/b3fe06dc-2f9f-40af-9faa-c17933106c4f/v2/assistants/593b6b5d-b627-4a4e-8a97-c9a696f0819a/sessions/v2/assistants/593b6b5d-b627-4a4e-8a97-c9a696f0819a/sessions?version=2020-04-13, ErrorCode: 404, Error: HTTP/1.1 404 Not Found, Response: {"error":"Resource not found","code":404}
UnityEngine.Debug:LogError(Object)

Thank you so much for this repo, it's so helpful.

**Comment by Aoost** [comment]
> > As of 01/28/2020 7PM CDT time zone, this Unity Project works with Unity 2017.2.8f1, IBM Unity SDK 4.1.1, and Unity SDK core 1.2.0. I'm pretty sure it will work with IBM Unity SDK 4.3.0. You just need to delete the unity-sdk-4.1.1 folder and replace it with unity-sdk-4.3.0. I fixed the mistake of not using the Watson service URLs correctly. So, it should now work with different IBM cloud regions. I've only tried it using the Dallas, Washington DC, and London regions.
> 
> Hi there, I'm getting what looks to be a similar error when I copy my service url verbatim. Not sure where you are adding the repeated lines though?
> ERROR] URL: https://api.us-south.assistant.watson.cloud.ibm.com/instances/b3fe06dc-2f9f-40af-9faa-c17933106c4f/v2/assistants/593b6b5d-b627-4a4e-8a97-c9a696f0819a/sessions/v2/assistants/593b6b5d-b627-4a4e-8a97-c9a696f0819a/sessions?version=2020-04-13, ErrorCode: 404, Error: HTTP/1.1 404 Not Found, Response: {"error":"Resource not found","code":404}
> UnityEngine.Debug:LogError(Object)
> 
> Thank you so much for this repo, it's so helpful.

FYI, TTS and STT both seem to be working...

**Comment by snhwang** [comment]
Hi. I think what constitutes the "service_url" is unclear, especially by web access, where I think IBM often just indicates "url." Are you entering more than "https://api.us-south.assistant.watson.cloud.ibm.com/instances/b3fe06dc-2f9f-40af-9faa-c17933106c4f" into the "service_url" in Unity? I think IBM shows this shorter url in on one page but shows the longer version with the additional information on another page. I apologize if I indicated the wrong one in the instructions.

**Comment by Aoost** [comment]
Appears I may have been using the incorret API Key bygoing via Watson Assistants rather than Resources, however, I am still getting: 
[04/10/2020 20:18:38][Unity][CRITICAL] Unity Exception NullReferenceException: Object reference not set to an instance of an object : SimpleBot.OnMessage (IBM.Cloud.SDK.DetailedResponse`1[T] response, IBM.Cloud.SDK.IBMError error) (at Assets/Scripts/SimpleBot.cs:222)
IBM.Watson.Assistant.V2.AssistantService.OnMessageResponse (IBM.Cloud.SDK.Connection.RESTConnector+Request req, IBM.Cloud.SDK.Connection.RESTConnector+Response resp) (at Assets/unity-sdk-4.5.0/Scripts/Services/Assistant/V2/AssistantService.cs:333)
IBM.Cloud.SDK.Connection.RESTConnector+<ProcessRequestQueue>d__33.MoveNext () (at Assets/unity-sdk-core-1.2.0/Connection/RESTConnector.cs:646)
IBM.Cloud.SDK.Utilities.Runnable+Routine.MoveNext () (at Assets/unity-sdk-core-1.2.0/Utilities/Runnable.cs:131)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

And 

NullReferenceException: Object reference not set to an instance of an object
SimpleBot.OnMessage (IBM.Cloud.SDK.DetailedResponse`1[T] response, IBM.Cloud.SDK.IBMError error) (at Assets/Scripts/SimpleBot.cs:222)

**Comment by Aoost** [comment]
> Hi. I think what constitutes the "service_url" is unclear, especially by web access, where I think IBM often just indicates "url." Are you entering more than "https://api.us-south.assistant.watson.cloud.ibm.com/instances/b3fe06dc-2f9f-40af-9faa-c17933106c4f" into the "service_url" in Unity? I think IBM shows this shorter url in on one page but shows the longer version with the additional information on another page. I apologize if I indicated the wrong one in the instructions.

I have found the correct URL but am still running into an issue, thank you so much for such a speedy response!

**Comment by snhwang** [comment]
An you're very welcome. I'm glad you found it useful. If you haven't yet, you should check out their latest IBM Cloud API documentation. They used to have code for different languages before but hey added more, including code for Unity. I would have bee able to do this project much faster if they had this last year.

**Comment by Aoost** [comment]
> Appears I may have been using the incorret API Key bygoing via Watson Assistants rather than Resources, however, I am still getting:
> [04/10/2020 20:18:38][Unity][CRITICAL] Unity Exception NullReferenceException: Object reference not set to an instance of an object : SimpleBot.OnMessage (IBM.Cloud.SDK.DetailedResponse`1[T] response, IBM.Cloud.SDK.IBMError error) (at Assets/Scripts/SimpleBot.cs:222)
> IBM.Watson.Assistant.V2.AssistantService.OnMessageResponse (IBM.Cloud.SDK.Connection.RESTConnector+Request req, IBM.Cloud.SDK.Connection.RESTConnector+Response resp) (at Assets/unity-sdk-4.5.0/Scripts/Services/Assistant/V2/AssistantService.cs:333)
> IBM.Cloud.SDK.Connection.RESTConnector+d__33.MoveNext () (at Assets/unity-sdk-core-1.2.0/Connection/RESTConnector.cs:646)
> IBM.Cloud.SDK.Utilities.Runnable+Routine.MoveNext () (at Assets/unity-sdk-core-1.2.0/Utilities/Runnable.cs:131)
> UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
> 
> And
> 
> NullReferenceException: Object reference not set to an instance of an object
> SimpleBot.OnMessage (IBM.Cloud.SDK.DetailedResponse`1[T] response, IBM.Cloud.SDK.IBMError error) (at Assets/Scripts/SimpleBot.cs:222)

Am I correct in using the Resources Asssitnat API key and URL with the particular Assistant I want to use's ID?

Not sure why I am running into this NullReferenceExeption

**Comment by snhwang** [comment]
That should be correct. Can you check the Chat, Text-to-speech, and speech-to-text prefabs in the Unity hierarchy in the Inspector? Prefabs are convenient but sometimes the links with gameobjects, etc. get messed up. Make sure the WatsonSettings.asset file is present in each of them.

**Comment by snhwang** [comment]
I deleted my WatsonSettings before I uploaded to Github. This may have messed up the prefabs.

**Comment by Aoost** [comment]
I have it assigned in each of the services. 
Is it worth making a new one? Strange because it seems to running the TTS and STT just fine.

**Comment by Aoost** [comment]
BTW I am running 2019.2.21f1(Stable right now) but that shouldn't have anything to do with it... 

What should the version date be?

**Comment by Aoost** [comment]
I am using 2020-04-01 as per https://cloud.ibm.com/apidocs/assistant/assistant-v2

**Comment by snhwang** [comment]
Possibly, if you're sure the API key and URL are now correct. I like Unity but sometimes it doesn't work for me. I do it again and then it seems to work without me knowing what I did differently. I have a meeting soon but I'll give this more though afterwards.

**Comment by Aoost** [comment]
> I deleted my WatsonSettings before I uploaded to Github. This may have messed up the prefabs.

I have populated and attached my Watson Settings file. (forgot to quote)

**Comment by snhwang** [comment]
Before I go, I'm not sure which API key you used, but the correct URL and API key should be the one when you first open up your Assistant from the Resources list.

**Comment by Aoost** [comment]
> Before I go, I'm not sure which API key you used, but the correct URL and API key should be the one when you first open up your Assistant from the Resources list.

I have now used the URL and API key from the assistant from Resources List along with the particular assistant ID which I'd like to be using (I have a few different ones associated with the service)

This seems to have resolved the 404 error, but I am still getting the Null Reference Exception which is what your Simple Bot is choking on, I believe (see second error)
![IBM Assistant Errors](https://user-images.githubusercontent.com/29804190/79022546-738b0900-7b3b-11ea-994b-66a74ed30bf3.png)

**Comment by snhwang** [comment]
I think you're right. The URL and credentials seem to be correct since the program is progessing to lines 222 in SimpleBot.cs, which is:   
`textResponse = response.Result.Output.Generic[0].Text.ToString();`   
unless you modified it. It also reched line 333 of AssistantServices.cs in the OnMessageReponse function. So, the error seems to have something to do with the response. I created a new Assistant using the Customer Care Sample Skill. When I deleted the Opening Box and the "Anything Else" box of the Assistant dialog, so that the chat doesn't have a response, I get errors on similar lines of code but not exactly the same error message. But, can you still check that your dialog has an opening/welcome response and a response if everything else fails? If your chat bot doesn't have opening/welcome response you can delete line 15 of chatcontrol.cs, which is just the Start() function calling for the welcome response. Another thing to try is to create a new chat bot using the Customer Care Sample Skill to make sure this works with your project. I just did it again to make sure, so it should work.

**Comment by snhwang** [comment]
I just noticed your earlier message about the Unity version. The project on Github presently is for Unity 2019.3.7f1. Unity doesn't support importing projects into a lower version of Unity, so it is possible that something could become broken. I tried this before, and it didn't work. If you create a new project and installed Unity-IBM SDK and the scripts into the new project then I think it should work with 2019.2.21f1. Maybe I'm doing any favors by updating the Unity version so frequently. I'll wait to the next LTS version before doing it again.

**Comment by Aoost** [comment]
We try to stay on top of the latest stable release, 2019.3 is in alpha right now, so will wait before refactoring for it.

**Comment by Aoost** [comment]
> I think you're right. The URL and credentials seem to be correct since the program is progessing to lines 222 in SimpleBot.cs, which is:
> `textResponse = response.Result.Output.Generic[0].Text.ToString();`
> unless you modified it. It also reched line 333 of AssistantServices.cs in the OnMessageReponse function. So, the error seems to have something to do with the response. I created a new Assistant using the Customer Care Sample Skill. When I deleted the Opening Box and the "Anything Else" box of the Assistant dialog, so that the chat doesn't have a response, I get errors on similar lines of code but not exactly the same error message. But, can you still check that your dialog has an opening/welcome response and a response if everything else fails? If your chat bot doesn't have opening/welcome response you can delete line 15 of chatcontrol.cs, which is just the Start() function calling for the welcome response. Another thing to try is to create a new chat bot using the Customer Care Sample Skill to make sure this works with your project. I just did it again to make sure, so it should work.

Hmm, that could be it, I have a conversation_start and a node that is triggered for anything_else in my bot but not the original one.

I just searched my unity project and chatcontrol.cs doesn't exist? Am I missing something? I will also try to connect it to another Assistant, and also make a new project that I'll copy the files into.

**Comment by snhwang** [comment]
Sorry. I meant botcontrol.cs, not chatcontrol.cs. I didn't think Unity 2019.3 alpha. I thought the Unity Hub just showed current official releases  and sometimes preleases(beta). Does is vary by region?

**Comment by snhwang** [comment]
I'll add a check to make sure the the response is not null before trying to use it.

**Comment by Aoost** [comment]
> Sorry. I meant botcontrol.cs, not chatcontrol.cs. I didn't think Unity 2019.3 alpha. I thought the Unity Hub just showed current official releases and sometimes preleases(beta). Does is vary by region?

Thanks! Will see if removing that call makes any difference. 

![Unity2019 3 alpha](https://user-images.githubusercontent.com/29804190/79034809-28421c00-7b76-11ea-9a19-b0c289b5154f.png)

**Comment by Aoost** [comment]
I got it to work on the customer care example skill!

Not exactly sure what I'm missing, but I'll take a look. Thanks so much for your help! I guess Unity can do backwards compatibility for this project

**Comment by snhwang** [comment]
Awesome! And you're welcome. I'm glad you got something working. Like I mentioned, I'll add a check to see if the response is empty. It still wouldn't really work but at least it won't crash.
